# Base is Omarchy. 
# Whatever comes next are personal preferences

# General
general {
    gaps_in = 2
    gaps_out = 4

    border_size = 1
    col.active_border = rgba(ffffff88)
    col.inactive_border = rgba(ffffff22)
}

decoration {
    rounding = 2
}

# Inputs
input {
    kb_layout = us,lt
    kb_options = compose:caps,grp:alt_space_toggle
    touchpad {
        natural_scroll = true
        scroll_factor = 0.125
        scroll_factor = 0.5, class:^(Ghostty|ghostty|Zed|zed)$
        clickfinger_behavior = true
    }
}


# Window Rules
windowrule = opacity 1, class:.*
windowrule = scrolltouchpad 2.0, class:^(Ghostty|ghostty|Zed|zed)$

# Gestures
gestures {
    workspace_swipe = true
}
